/**
 * All dropdown / multi-select option data for the submission form.
 * Single source of truth — imported by page.tsx and utils.ts.
 * Data sourced from gener8tor Northwestern Mutual Accelerator form (scraped 2026-03-29).
 */

// 122 industries — canonical list
export const INDUSTRY_OPTIONS = [
  "Administrative Services", "Advanced Technology", "Advertising",
  "Agriculture and Farming", "All Industries / Industry Agnostic", "Apps",
  "Architecture & Planning", "Artificial Intelligence", "Automotive",
  "Aviation Aerospace", "Banking", "Biotechnology", "Building Materials",
  "Clothing and Apparel", "Commerce and Shopping", "Community and Lifestyle",
  "Computer Games", "Computer Software", "Construction", "Consumer Electronics",
  "Consumer Goods", "Consumer Services", "Content and Publishing",
  "Data and Analytics", "Defense & Space", "Design", "Digital Health",
  "E-Learning", "Education", "Electrical & Electronic Manufacturing",
  "Electrical Manufacturing", "Energy", "Entertainment", "Environmental Services",
  "Events", "Farming", "Fashion", "Financial Services",
  "Financial Technology (FinTech)", "Food & Beverage", "Furniture", "Gaming",
  "Government Administration", "Government and Military", "Hardware",
  "Health Care", "Higher Education", "Hospital & Health Care", "Human Resources",
  "Information Technology", "Information Technology & Services", "Insurance",
  "Insurance Technology (InsureTech)", "Internet", "Internet Services",
  "Investment Management", "Legal Service", "Leisure, Travel & Tourism",
  "Lending and Investments", "Life Sciences", "Logistics & Supply Chain",
  "Machinery", "Management Consulting", "Manufacturing",
  "Marketing & Advertising", "Mechanical Or Industrial Engineering",
  "Media and Entertainment", "Media Production", "Medical Device",
  "Messaging and Telecommunications", "Mobile", "Music", "Music and Audio",
  "Natural Resources", "Navigation and Mapping",
  "Non-profit Organization Management", "Oil and Energy",
  "Outsourcing/Offshoring", "Packaging & Containers", "Payments",
  "Payroll & Benefits", "Pharmaceuticals", "Platforms",
  "Primary/Secondary Education", "Privacy and Security",
  "Professional Services", "Program Development", "Publishing", "Real Estate",
  "Restaurants", "Retail", "Robotics & Automation",
  "Safety & Regulatory Compliance", "Sales and Marketing",
  "Science and Engineering", "Security & Investigations", "Social Impact",
  "Software", "Sporting Goods", "Sports", "Staffing & Recruiting",
  "Sustainability", "Telecommunications", "Transportation",
  "Travel and Tourism", "Venture Capital Private Equity", "Video", "Wholesale",
  "Workforce", "Nature-Based Solutions", "Built Environment",
  "Emissions Removal", "Capture & Storage", "Circular Economy",
  "Adaptation & Resilience", "Industrial Innovation", "Advanced Energy",
  "Food & Agriculture", "Materials & Textiles", "Water",
  "Transportation & Mobility", "Other",
] as const;

export const INDUSTRY_PRIORITY_OPTIONS = [
  "Data and Analytics",
  "Insurance Technology (InsureTech)",
  "Digital Health",
  "Financial Technology (FinTech)",
  "None",
] as const;

export const KEYWORD_OPTIONS = [
  "3D Printing", "3D Technology", "A/B Testing", "Accounting", "Ad Exchange",
  "Ad Network", "Ad Retargeting", "Ad Server", "Ad Targeting",
  "Advanced Materials", "Adventure Travel", "Advertising",
  "Advertising Platforms", "Advice", "Aerospace", "Affiliate Marketing",
  "Ag Bio Tech", "Ag Fintech", "Agriculture", "AgTech", "Air Transportation",
  "Alt Proteins", "Alternative Medicine", "Alumni", "American Football",
  "Amusement Park and Arcade", "Analytics", "Android", "Angel Investment",
  "Animal Feed", "Animal Health", "Animal Proteins", "Animation",
  "App Discovery", "App Marketing", "Application Performance Management",
  "Application Specific Integrated Circuit (ASIC)", "Apps", "Aquaculture",
  "Architecture", "Archiving Service", "Art", "Artificial Intelligence",
  "Asset Management", "Assisted Living", "Assistive Technology", "Association",
  "Auctions", "Audio", "Audiobooks", "Augmented Reality", "Auto Insurance",
  "Automotive", "Autonomous Vehicles", "B2B", "B2C", "Bakery", "Banking",
  "Baseball", "Basketball", "Battery", "Beauty", "BECCS", "Big Data",
  "Billing", "Biochar", "Biofuel", "Bioinformatics",
  "Biological CO2 Conversion", "Biomass Energy", "Biometrics", "Biopharma",
  "Biotechnology", "Bitcoin", "Blockchain", "Blogging Platforms", "Boating",
  "Brand Marketing", "Brewing", "Broadcasting", "Browser Extensions",
  "Building Maintenance", "Building Material", "Business Development",
  "Business Information Systems", "Business Intelligence", "Business Travel",
  "CAD", "Call Center", "Cannabis/Hemp", "Car Sharing",
  "Carbon Sequestration & Markets", "Career Planning", "Casino",
  "Casual Games", "Catering", "Cause Marketing", "CEA", "Celebrity",
  "Charity", "Charter Schools", "Chemical", "Chemical Engineering",
  "Child Care", "Children", "CivicTech", "Civil Engineering", "Classifieds",
  "Clean Energy", "CleanTech", "Clinical Trials", "Cloud Computing",
  "Cloud Data Services", "Cloud Infrastructure", "Cloud Management",
  "Cloud Security", "Cloud Storage", "CMS", "Coffee", "Collaboration",
  "Collaborative Consumption", "Collectibles", "Collection Agency",
  "College Recruiting", "Comics", "Commercial", "Commercial Insurance",
  "Commercial Lending", "Commercial Real Estate", "Communication Hardware",
  "Communications Infrastructure", "Communities", "Compliance", "Computer",
  "Computer Vision", "Concerts", "Confectionery", "Console Games",
  "Construction", "Consulting", "Consumer", "Consumer Applications",
  "Consumer Electronics", "Consumer Goods", "Consumer Lending",
  "Consumer Research", "Consumer Reviews", "Consumer Software",
  "Contact Management", "Content", "Content Creators",
  "Content Delivery Network", "Content Discovery", "Content Marketing",
  "Content Syndication", "Contests", "Continuing Education", "Cooking",
  "Corporate Training", "Cosmetic Surgery",
  "Cosmetics", "Coupons", "Courier Service", "Coworking", "CPG",
  "Craft Beer", "Creative Agency", "Credit", "Credit Bureau", "Credit Cards",
  "Cricket", "CRM", "Crop Inputs", "Crop Management", "Crowdfunding",
  "Crowdsourcing", "Cryptocurrency", "Customer Service", "Cyber Security",
  "Cybersecurity", "Cycling", "Darknet", "Data Center",
  "Data Center Automation", "Data Integration", "Data Mining",
  "Data Storage", "Data Visualization", "Database", "Dating", "Debit Cards",
  "Debt Collections", "Delivery", "Delivery Service", "Dental",
  "Desktop Apps", "Developer APIs", "Developer Platform", "Developer Tools",
  "Diabetes", "Dietary Supplements", "Digital Entertainment",
  "Digital Livestock", "Digital Marketing", "Digital Media",
  "Digital Signage", "Direct Marketing", "Direct Sales", "Distillery",
  "Diving", "DIY", "Document Management", "Document Preparation",
  "Domain Registrar", "DRM", "Drone Management", "Drones", "DSP",
  "E-Commerce", "E-Commerce Platforms", "E-Learning", "E-Signature",
  "EBooks", "Ediscovery", "EdTech", "Education", "Edutainment",
  "Elder Care", "Electric Vehicle", "Electrical Distribution",
  "Electrochemical CO2 Conversion", "Electronic Design Automation (EDA)",
  "Electronic Health Record (EHR)", "Electronics", "Email",
  "Email Marketing", "Embedded Software", "Embedded Systems",
  "Emergency Medicine", "Emerging Markets", "Employee Benefits",
  "Employment", "Energy", "Energy Efficiency", "Energy Management",
  "Energy Storage", "Engineered DAC", "Enterprise",
  "Enterprise Applications", "Enterprise Resource Planning (ERP)",
  "Enterprise Software", "Environmental Consulting",
  "Environmental Engineering", "Equestrian", "eSports", "Ethereum",
  "Event Management", "Event Promotion", "Events",
  "Extermination Service", "Eye Care", "Eyewear", "Facebook",
  "Facial Recognition", "Facilities Support Services",
  "Facility Management", "Family", "Fantasy Sports", "Farm Machinery",
  "Farm Operations", "Farmers Market", "Farming", "Fashion",
  "Fast-Moving Consumer Goods", "Ferry Service", "Fertility",
  "Field Support", "Field-Programmable Gate Array (FPGA)",
  "File Sharing", "Film", "Film Distribution", "Film Production",
  "Finance", "Financial Exchanges", "Financial Services", "FinTech",
  "First Aid", "Fitness", "Flash Sale", "Flash Storage",
  "Fleet Management", "Flowers", "Food & Beverage",
  "Food & Produce Distribution/Marketplaces", "Food and Beverage",
  "Food Delivery", "Food Ingredient Processing", "Food Ingredients",
  "Food Manufacturing", "Food Preservation", "Food Processing",
  "Food Trucks", "Food Waste Reduction", "Forestry", "Fossil Fuels",
  "Foundries", "Franchise", "Fraud Detection", "Freelance", "Freemium",
  "Freight Service", "Fruit", "Fuel", "Fuel Cell", "Funding Platform",
  "Funerals", "Furniture", "Gambling", "Gamification", "Gaming",
  "Generation Y", "Generation Z", "Genetics", "Geologic Storage",
  "Geospatial", "Gift Card", "Gift Exchange", "Gift Registry", "Gifts",
  "Golf", "Google", "Google Glass", "Government", "GovTech", "GPS", "GPU",
  "Graphic Design", "Green Building", "Green Consumer Goods", "GreenTech",
  "Grocery", "Group Buying", "Guides", "Handmade", "Hardware",
  "Health Care", "Health Diagnostics", "Health Insurance", "Hedge Funds",
  "Higher Education", "Hockey", "Home and Garden", "Home Decor",
  "Home Health Care", "Home Improvement", "Home Renovation",
  "Home Services", "Homeland Security",
  "Horticulture", "Hospital", "Hospitality", "Hotel",
  "Housekeeping Service", "Human Computer Interaction",
  "Human Health/Nutrition", "Human Resources", "Humanitarian", "Hunting",
  "Hydroponics", "IaaS", "Identity Management", "Image Recognition",
  "Impact Investing", "In-Flight Entertainment", "Incubators",
  "Independent Music", "Indoor Positioning", "Industrial",
  "Industrial Automation", "Industrial Design", "Industrial Engineering",
  "Industrial Manufacturing", "Infant Health",
  "Information and Communications Technology (ICT)",
  "Information Services", "Information Technology", "Infrastructure",
  "Innovation Management", "Insurance", "InsurTech",
  "Intellectual Property", "Intelligent Systems", "Interior Design",
  "Internet", "Internet of Things", "Internet Radio",
  "Intrusion Detection", "iOS", "IoT/Remote Sensing", "Irrigation Tech",
  "ISP", "IT Infrastructure", "IT Management", "Janitorial Service",
  "Jewelry", "Journalism", "Knowledge Management", "Land Based CDR",
  "Landscaping", "Language Learning", "Laser",
  "Last Mile Transportation", "Laundry and Dry-cleaning",
  "Law Enforcement", "Lead Generation", "Lead Management", "Leasing",
  "Legal", "Legal Tech", "Leisure", "Lending", "Life Insurance",
  "Life Science", "Lifestyle", "Lighting", "Limousine Service",
  "Lingerie", "Linux", "Livestock", "Livestock Equipment",
  "Livestock Genetics", "Local", "Local Advertising", "Local Business",
  "Local Shopping", "Location Based Services", "Logistics",
  "Loyalty Programs", "Machine Learning", "Machinery Manufacturing",
  "macOS", "Made to Order", "Management Consulting",
  "Management Information Systems", "Manufacturing",
  "Mapping Services", "Marine Technology", "Marine Transportation",
  "Market Research", "Marketing", "Marketing Automation", "Marketplace",
  "Maternal Health", "Mechanical Design", "Mechanical Engineering",
  "Media and Entertainment", "Medical", "Medical Device",
  "Meeting Software", "Men's Products", "Mental Health", "Messaging",
  "Metaverse", "mHealth", "Micro Lending", "Military", "Millennials",
  "Mineral", "Mineralization", "Mining", "Mining Technology",
  "MMO Games", "Mobile", "Mobile Advertising", "Mobile Apps",
  "Mobile Devices", "Mobile Payments", "MOOC", "Motion Capture",
  "Multi-level Marketing", "Museums and Historical Sites", "Music",
  "Music Education", "Music Label", "Music Streaming", "Music Venues",
  "Musical Instruments", "Nanotechnology", "National Security",
  "Natural Language Processing", "Natural Resources", "Navigation",
  "Network Hardware", "Network Security", "Neuroscience", "News", "NFC",
  "Nightclubs", "Nightlife", "Nintendo", "Non Profit", "Nuclear",
  "Nursing and Residential Care", "Nutraceutical", "Nutrition",
  "Ocean Based CDR", "Office Administration", "Oil and Gas",
  "Online Auctions", "Online Forums", "Online Games", "Online Portals",
  "Open Source", "Operating Systems", "Optical Communication", "Organic",
  "Organic Food", "Other CO2 Capture", "Other CO2 Storage",
  "Outdoor Advertising", "Outdoors", "Outpatient Care", "Outsourcing",
  "PaaS", "Packaging Services", "Paper Manufacturing", "Parenting",
  "Parking", "Parks", "Payments", "PC Games", "Pediatrics",
  "Peer to Peer", "Penetration Testing", "Performing Arts",
  "Personal Branding", "Personal Development", "Personal Finance",
  "Personal Health", "Personalization", "Pet", "Pharmaceutical",
  "Photo Editing", "Photo Sharing", "Photochemical CO2 Conversion",
  "Photography", "Physical Security",
  "Plastics and Rubber Manufacturing", "Playstation", "Podcast",
  "Point of Sale", "Point Source Capture", "Politics",
  "Pollution Control", "Ports and Harbors", "Power Grid",
  "Precious Metals", "Prediction Markets", "Predictive Analytics",
  "Presentation Software", "Presentations", "Price Comparison",
  "Primary Education", "Printing", "Privacy", "Private Cloud",
  "Private Social Networking", "Procurement", "Product Design",
  "Product Research", "Product Search", "Productivity Tools",
  "Professional Networking", "Professional Services",
  "Project Management", "Property Development", "Property Insurance",
  "Property Management", "Psychology", "Public Relations",
  "Public Safety", "Public Transportation", "Publishing", "QR Codes",
  "Quality Assurance", "Quantified Self", "Quantum Computing", "Racing",
  "Railroad", "Reading Apps", "Real Estate", "Real Estate Investment",
  "Real Time", "Recipes", "Recreation", "Recreational Vehicles",
  "Recruiting", "Recycling", "Rehabilitation", "Religion",
  "Renewable Energy", "Rental", "Rental Property",
  "Reproductive Health", "Reputation", "Reservations", "Residential",
  "Resorts", "Restaurants", "Retail", "Retail Technology", "Retirement",
  "RFID", "Ride Sharing", "RISC", "Risk Management", "Robotics",
  "Robotics & Automation", "Roku", "Rugby", "SaaS", "Sailing", "Sales",
  "Sales Automation", "Same Day Delivery", "Satellite Communication",
  "Scheduling", "Seafood", "Search Engine", "Secondary Education",
  "Security", "Self-Storage", "SEM", "Semantic Search", "Semantic Web",
  "Semiconductor", "Sensor", "SEO", "Serious Games", "Service Industry",
  "Sharing Economy", "Shipping",
  "Shipping Broker", "Shoes", "Shopping", "Shopping Mall", "Simulation",
  "Skiing", "Skill Assessment", "Small and Medium Businesses",
  "Smart Building", "Smart Cities", "Smart Home", "SMS", "Snack Food",
  "SNS", "Soccer", "Social", "Social Assistance", "Social Bookmarking",
  "Social CRM", "Social Entrepreneurship", "Social Impact",
  "Social Media", "Social Media Advertising",
  "Social Media Management", "Social Media Marketing",
  "Social Network", "Social News", "Social Recruiting",
  "Social Shopping", "Software", "Software Engineering", "Solar",
  "Space Travel", "Spam Filtering", "Speech Recognition", "Sponsorship",
  "Sporting Goods", "Sports", "Staffing Agency", "STEM Education",
  "Stock Exchanges", "Subscription Service", "Supply Chain Management",
  "Surfing", "Sustainability", "Sustainability & Regenerative Farming",
  "Swimming", "Table Tennis", "Task Management", "Taxi Service", "Tea",
  "Technical Support", "Teenagers", "Telecommunications", "Tennis",
  "Test and Measurement", "Text Analytics", "Textbook", "Textiles",
  "Theatre", "Therapeutics", "Thermochemical CO2 Conversion",
  "Ticketing", "Timber", "Timeshare", "Tobacco", "Tour Operator",
  "Tourism", "Toys", "Trade Shows", "Trading Platform", "Training",
  "Transaction Processing", "Translation Service", "Transportation",
  "Travel", "Travel Accommodations", "Travel Agency", "Tutoring", "TV",
  "TV Production", "Twitter", "Ultimate Frisbee",
  "Unified Communications", "Universities", "Usability Testing",
  "UX Design", "Vacation Rental", "Vending and Concessions",
  "Venture Capital", "Vertical Search", "Veterinary", "Video",
  "Video Advertising", "Video Chat", "Video Conferencing",
  "Video Editing", "Video Games", "Video on Demand", "Video Streaming",
  "Virtual Assistant", "Virtual Currency", "Virtual Desktop",
  "Virtual Goods", "Virtual Reality", "Virtual Workforce",
  "Virtual World", "Virtualization", "Visual Search",
  "Vocational Education", "VoIP", "Volley Ball", "Warehousing",
  "Waste Management", "Water", "Water Purification",
  "Water Transportation", "Wealth Management", "Wearables", "Web Apps",
  "Web Browsers", "Web Design", "Web Development", "Web Hosting",
  "Web3", "WebOS", "Wedding", "Wellness", "Wholesale", "Wind Energy",
  "Windows", "Windows Phone", "Wine And Spirits", "Winery", "Wired",
  "Wireless", "Women's Products", "Wood Processing", "Wound Care",
  "Xbox", "Young Adults",
] as const;

export const COUNTRY_OPTIONS = [
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola",
  "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria",
  "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus",
  "Belgium", "Belize", "Benin", "Bhutan", "Bolivia",
  "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria",
  "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia", "Cameroon",
  "Canada", "Central African Republic", "Chad", "Chile", "China",
  "Colombia", "Comoros", "Congo (Congo-Brazzaville)", "Costa Rica",
  "Croatia", "Cuba", "Cyprus", "Czechia (Czech Republic)",
  "Democratic Republic of the Congo", "Denmark", "Djibouti", "Dominica",
  "Dominican Republic", "Ecuador", "Egypt", "El Salvador",
  "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Fiji",
  "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana",
  "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana",
  "Haiti", "Honduras", "Hong Kong", "Hungary", "Iceland", "India",
  "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Jamaica",
  "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kuwait",
  "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia",
  "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Madagascar",
  "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands",
  "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco",
  "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia",
  "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger",
  "Nigeria", "North Korea", "North Macedonia", "Norway", "Oman",
  "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea",
  "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar",
  "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia",
  "Saint Vincent and the Grenadines", "Samoa", "San Marino",
  "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia",
  "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia",
  "Solomon Islands", "Somalia", "South Africa", "South Korea",
  "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden",
  "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand",
  "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia",
  "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine",
  "United Arab Emirates", "United Kingdom", "United States of America",
  "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Yemen",
  "Zambia", "Zimbabwe", "Other",
] as const;

export const STAGE_OPTIONS = [
  "Not Sure / Not Applicable",
  "Pre-Seed",
  "Seed",
  "Seed II",
  "Seed III",
  "Series A",
  "Series B",
  "Series C",
  "Series D or Higher",
  "Bootstrapped",
] as const;

export const BUSINESS_MODEL_OPTIONS = [
  "SaaS Subscription",
  "Marketplace",
  "Usage-Based",
  "Enterprise License",
  "Freemium",
  "Hardware + Software",
  "Services",
  "Other",
] as const;

export const REVENUE_OPTIONS = [
  "Pre-revenue",
  "$0-10K",
  "$10K-50K",
  "$50K-100K",
  "$100K-500K",
  "$500K-1M",
  "$1M-5M",
  "$5M+",
] as const;

export const FUNDING_OPTIONS = [
  "Unfunded",
  "Pre-seed (<$500K)",
  "Seed ($500K-$2M)",
  "Series A ($2M-$15M)",
  "Series B+ ($15M+)",
  "Bootstrapped (profitable)",
] as const;

export const PRICING_MODEL_OPTIONS = [
  "Per Seat",
  "Subscription",
  "Usage-Based",
  "Enterprise Annual Contract",
  "Transaction Fee",
  "Services",
  "Hybrid",
  "Other",
] as const;

export const SALES_MOTION_OPTIONS = [
  "Self-Serve",
  "Founder-Led Sales",
  "Inside Sales",
  "Enterprise Sales",
  "Channel / Partners",
  "Outbound-Led",
  "Other",
] as const;

export const IMPLEMENTATION_COMPLEXITY_OPTIONS = [
  "Self-Serve",
  "Light Integration",
  "Heavy Integration",
  "On-Prem / Complex Deployment",
  "Not Sure",
] as const;

export const CURRENT_SUBSTITUTE_OPTIONS = [
  "Spreadsheets",
  "Manual Workflow",
  "Incumbent Software",
  "In-House Tools",
  "Consultants / Agencies",
  "Do Nothing",
  "Other",
] as const;

export const PRIMARY_RISK_OPTIONS = [
  "Sales / GTM",
  "Technical Execution",
  "Adoption / Behavior Change",
  "Competition",
  "Capital Intensity",
  "Regulatory / Compliance",
  "Supply Chain / Operations",
  "Team / Hiring",
  "Other",
] as const;

export const REFERRAL_SOURCE_OPTIONS = [
  "Search Engine",
  "Social Media (Twitter/X, LinkedIn)",
  "Referral from another founder",
  "Accelerator / Incubator",
  "Venture Capital / Investor",
  "Product Hunt",
  "Tech Media / Blog",
  "Other",
] as const;
