export const browserCoreExamples = [
  "mirai browser status",
  "mirai browser start",
  "mirai browser stop",
  "mirai browser tabs",
  "mirai browser open https://example.com",
  "mirai browser focus abcd1234",
  "mirai browser close abcd1234",
  "mirai browser screenshot",
  "mirai browser screenshot --full-page",
  "mirai browser screenshot --ref 12",
  "mirai browser snapshot",
  "mirai browser snapshot --format aria --limit 200",
  "mirai browser snapshot --efficient",
  "mirai browser snapshot --labels",
];

export const browserActionExamples = [
  "mirai browser navigate https://example.com",
  "mirai browser resize 1280 720",
  "mirai browser click 12 --double",
  'mirai browser type 23 "hello" --submit',
  "mirai browser press Enter",
  "mirai browser hover 44",
  "mirai browser drag 10 11",
  "mirai browser select 9 OptionA OptionB",
  "mirai browser upload /tmp/openclaw/uploads/file.pdf",
  'mirai browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "mirai browser dialog --accept",
  'mirai browser wait --text "Done"',
  "mirai browser evaluate --fn '(el) => el.textContent' --ref 7",
  "mirai browser console --level error",
  "mirai browser pdf",
];
